### ISSUE TITLE
启动后，cmd窗口闪几次没有任何反应

### ISSUE THREAD

**Issue by 2497162852** [KL-kirito/CelestiaLauncher#10]
按照顺序安装完之后，启动cmd窗口会闪退几次![image](https://user-images.githubusercontent.com/33111780/170434208-3e7ca727-fcf5-455f-92cf-ad595e55b5ae.png)

**Comment by 2497162852** [comment]
![image](https://user-images.githubusercontent.com/33111780/170440178-5d6eee6c-3931-42c2-b27b-563c203c02c3.png)
第一次重装后没用

**Comment by 2497162852** [comment]
![image](https://user-images.githubusercontent.com/33111780/170445453-c3f70baf-6d88-4fb8-9372-282e989318f4.png)
第三次重装，在编译前准备时cmd就闪退，录屏截的图

**Comment by nullsora** [comment]
您的问题和Issue #9 是基本相同的。
对于没有问题修复完全，我在此深表歉意。
稍后版本将会修复问题。

**Comment by nullsora** [comment]
您可以下载最新版本来解决该问题了。
