### ISSUE TITLE
download failed. exit with code 128.

### ISSUE THREAD

**Issue by iEclipseYe** [KL-kirito/CelestiaLauncher#3]
![image](https://user-images.githubusercontent.com/105561109/168443350-878ed7b9-0088-4b60-9831-39daa41a05c5.png)

**Comment by nullsora** [comment]
如果已经存在了Grasscutter文件夹再次点击下载时，或网络不良好时会报错。
如果此前已经下载完成，请不要再次下载。
如果没有，那么你可能需要手动删除Grasscutter文件夹，后续版本会尽快修复该问题。
