### ISSUE TITLE
程序停止在 配置Grasscutter

### ISSUE THREAD

**Issue by xxnuo** [KL-kirito/CelestiaLauncher#4]
按照配置顺序顺利执行至第四步，执行配置Grasscutter后等很久程序也没有反应

查看任务管理器发现执行 xcopy 完成后到只有程序主进程，CPU内存和网络均无占用，但程序仍然不能操作。
等了大概有15分钟后，强制关闭窗口，重启启动器执行后续操作均正常，启动服务器后也正常，游戏进去也能用。

也不知道是卡在了哪一步，需要添加一个显示正在执行的任务信息的提示😢

**Comment by xxnuo** [comment]
![image](https://user-images.githubusercontent.com/54252779/168456426-9ef0636c-dc83-4a4d-95e8-78121d310726.png)

**Comment by nullsora** [comment]
异步执行命令已经完成开发，稍后就会更新1.0.2版本并解决该问题
