### ISSUE TITLE
win11平台下载完所需资源后配置中配置Grasscutter与编译前准备仍为灰色，且任务栏中图标下灰色小条仍在动态的滑动

### ISSUE THREAD

**Issue by czy20010112** [KL-kirito/CelestiaLauncher#5]
java与git都是下载并安装成功，mongodb只显示下载成功，进度条后面还是有一截没满 不清楚是不是正常的。
接下来下载grasscutter与resource 都显示success 
之后就如标题所示了 且配置页面左半部服务器配置那儿也全是灰色无法点击
主页的选择grasscutter文件夹这个选项点了也没用，不清楚什么情况。
任务管理器中该程序除了内存所有的占用都为0

**Comment by nullsora** [comment]
刚注意到了这个问题，已经修复完毕，等待几分钟后的新版本即可
深表歉意。

**Comment by czy20010112** [comment]
> 刚注意到了这个问题，已经修复完毕，等待几分钟后的新版本即可 深表歉意。

幸苦了
